import type { ScanResult, Violation } from "../types/index.js";

function getSeverityBadge(severity: Violation["severity"]): string {
  switch (severity) {
    case "critical":
      return "🔴 **CRITICAL**";
    case "high":
      return "🟠 **HIGH**";
    case "medium":
      return "🟡 **MEDIUM**";
    case "low":
      return "🔵 **LOW**";
  }
}

/**
 * 監査結果を GitHub PR / CI 向けの高品質な Markdown 文字列として生成
 */
export function formatMarkdownReport(result: ScanResult): string {
  const { summary, violations, timestamp, gitCommitHash } = result;

  const lines: string[] = [];

  lines.push("# 🛡️ shipguard Audit Report");
  lines.push("");
  lines.push(`> **Run Time:** ${timestamp}  `);
  if (gitCommitHash) {
    lines.push(`> **Commit:** \`${gitCommitHash.substring(0, 8)}\`  `);
  }
  lines.push(`> **Files Scanned:** ${summary.scannedFiles}  `);
  lines.push(
    summary.passed
      ? "> **Status:** ✅ **PASSED** (Ready to Deploy)"
      : "> **Status:** ❌ **FAILED** (Critical/High issues detected)"
  );
  lines.push("");

  // サマリー表
  lines.push("## 📊 Summary");
  lines.push("");
  lines.push("| Severity | Count |");
  lines.push("| :--- | :--- |");
  lines.push(`| 🔴 CRITICAL | ${summary.critical} |`);
  lines.push(`| 🟠 HIGH | ${summary.high} |`);
  lines.push(`| 🟡 MEDIUM | ${summary.medium} |`);
  lines.push(`| 🔵 LOW | ${summary.low} |`);
  lines.push(`| **Total Violations** | **${summary.totalViolations}** |`);
  lines.push("");

  // 違反詳細
  lines.push("## 🔍 Violations");
  lines.push("");

  if (violations.length === 0) {
    lines.push("🎉 **No violations detected. All security and configuration checks passed!**");
    lines.push("");
  } else {
    for (const [index, v] of violations.entries()) {
      const badge = getSeverityBadge(v.severity);
      const loc = `\`${v.filePath}:${v.line}${v.column ? `:${v.column}` : ""}\``;

      lines.push(`### ${index + 1}. [${v.ruleId}] ${v.ruleName}`);
      lines.push("");
      lines.push(`- **Severity:** ${badge}`);
      lines.push(`- **Location:** ${loc}`);
      lines.push(`- **Details:** ${v.message}`);

      if (v.snippet) {
        lines.push("");
        lines.push("```typescript");
        lines.push(v.snippet);
        lines.push("```");
      }
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("*Generated by [shipguard](https://github.com/tk030-lotto/shipguard) — Zero-cost local security auditor*");
  lines.push("");

  return lines.join("\n");
}
